services:
  threes-app:
    container_name: threes-app
    user: "1000:1000"
    environment:
      - APP_URL=https://os3.pro
      - BACKEND_URI=/console
      - DB_CONNECTION=pgsql
      - DB_HOST=threes-db
      - DB_PORT=5432
      - DB_DATABASE=threes
      - DB_USERNAME=threes
      - DB_PASSWORD=threes
      - LINK_POLICY=secure
    build:
      context: ./scripts
    restart: always
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    labels:
      - "traefik.enable=true"

      # Основной роутер для HTTPS
      - "traefik.http.routers.threes.rule=Host(`os3.pro`, `www.os3.pro`) && PathPrefix(`/`)"
      - "traefik.http.routers.threes.entrypoints=websecure"
      - "traefik.http.routers.threes.tls.certresolver=myresolver"
      - "traefik.http.services.threes.loadbalancer.server.port=80"

      # Редирект с www на non-www
      - "traefik.http.middlewares.redirect-www.redirectregex.regex=^https?://www\\.(.+)"
      - "traefik.http.middlewares.redirect-www.redirectregex.replacement=https://$1"
      - "traefik.http.middlewares.redirect-www.redirectregex.permanent=true"
      - "traefik.http.routers.threes.middlewares=redirect-www"

      # Редирект с HTTP на HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.threes-http.rule=Host(`os3.pro`, `www.os3.pro`)"
      - "traefik.http.routers.threes-http.entrypoints=web"
      - "traefik.http.routers.threes-http.middlewares=redirect-to-https"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/app
    networks:
      - web
  threes-db:
    container_name: threes-db
    image: postgres:15
    restart: always
    user: "1000:1000"
    ports:
      - "5488:5432"
    environment:
      POSTGRES_DB: os3home
      POSTGRES_USER: os3home
      POSTGRES_PASSWORD: os3home
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - web

networks:
  web:
    external: true