services:
  threes-app:
    container_name: threes-app
    user: "1000:1000"
    environment:
      - APP_URL=http://threes.dc
      - BACKEND_URI=/console
      - DB_CONNECTION=pgsql
      - DB_HOST=threes-db
      - DB_PORT=5432
      - DB_DATABASE=threes
      - DB_USERNAME=threes
      - DB_PASSWORD=threes
    build:
      context: ./scripts
    restart: always
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.threes.rule=Host(`threes.dc`) && PathPrefix(`/`)"
      - "traefik.http.routers.threes.entrypoints=web"
      - "traefik.http.services.threes.loadbalancer.server.port=80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/app
    networks:
      - web
  threes-db:
    container_name: threes-db
    image: postgres:15
    restart: always
    user: "1000:1000"
    ports:
      - "5488:5432"
    environment:
      POSTGRES_DB: threes
      POSTGRES_USER: threes
      POSTGRES_PASSWORD: threes
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - web

networks:
  web:
    external: true
